version: '3.8'

services:
  test:
    build: .
    container_name: test
    restart: always
    networks:
      - tunnel-net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    command: tunnel --url http://localhost:8080
    networks:
      - tunnel-net
    depends_on:
      - test

networks:
  tunnel-net:
    driver: bridge